# Generated by Django 6.1 on 2026-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initial', models.CharField(blank=True, max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=270)),
                ('sum_without_initial', models.IntegerField(default=0)),
                ('recursive_sum_without_initial', models.IntegerField(default=0)),
                ('sum', models.IntegerField(default=0)),
                ('recursive_sum', models.IntegerField(default=0)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at', 'name'],
            },
        ),
    ]
