# Generated by Django 6.1 on 2026-08-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('sum', models.IntegerField(default=0)),
                ('recursive_sum', models.IntegerField(default=0)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Name Entry',
                'verbose_name_plural': 'Name Entries',
                'ordering': ['-uploaded_at', 'name'],
            },
        ),
    ]
