# Generated by Django 6.1 on 2026-08-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameentry',
            options={'ordering': ['-uploaded_at', 'name'], 'verbose_name': 'Name Entry', 'verbose_name_plural': 'Name Entries'},
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='recursive_sum_without_initial',
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='sum_without_initial',
        ),
        migrations.AddField(
            model_name='nameentry',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
