# Generated by Django 6.1 on 2026-08-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0002_alter_nameentry_options_remove_nameentry_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameentry',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
