# Generated by Django 6.1 on 2026-08-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0003_nameentry_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameentry',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='nameentry',
            name='last_name',
        ),
    ]
